### ISSUE TITLE
error Error: Cannot find module '#entry'

### ISSUE THREAD

**Issue by ff131517** [shuidi-fed/vapper#101]
//vapper.config.js
```js
{
  clientEntry: './src/client.ts',
  serverEntry: './src/server.ts'
}
```
//yarn run dev
```js
error Error: Cannot find module '#entry'
    at webpackMissingModule (app.js:2660:45)
    at Module../node_modules/@vapper/core/app/createApp.js (app.js:2660:126)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../node_modules/@vapper/core/app/serverEntry.js (app.js:3030:69)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.0 (app.js:109014:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at app.js:118:18
    at Object.<anonymous> (app.js:121:10)
```

How can i fix this problem?

node:12.16.1
"@vapper/core": "^1.11.2"
"vue": "^2.6.11",

**Comment by kawendiyu** [comment]
entry
类型：string
默认值：'src/main'
指定项目的入口文件，默认遵守 Vue CLI 的约定，把 src/main.js 文件作为入口文件。如果你使用 Poi，那么你需要修改该选项为：'src/index.js'。

提示

entry 选项需要与 vue.config.js(或 poi.config.js) 配置文件中的 entry 选项保持一致。

这意思是不是讲main.js还得用
