### ISSUE TITLE
Can't get started with vue-cli: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by bpolaszek** [shuidi-fed/vapper#107]
Hello there,

I've been doing VueJS for 2 years and for the 1st time I have SSR requirements. What Vapper offers (hybrid SSR + SPA depending on routes) seems to fit really well!

However, even if I managed to make it work from your poi example, I didn't succeed with VueCli (which I'm more familiar).
Following your guide, here's what I've done:

```bash
vue create my-vapper-app && cd my-vapper-app # manuel preset: babel, router, vuex, vue 2.x, history mode enabled, dedicated config files
yarn add @vapper/core vue-router
# add scripts in package.json (I prefixed them with vapper:)
# change main.js with the entry file
yarn vapper:dev
```

<details>
<summary>And here's the result:</summary>
<p>

```
benoit@MacBook.local [master] /Users/benoit/Sandboxes/my-vapper-app$ yarn vapper:dev
yarn run v1.22.10
$ vapper dev
Error: ENOENT: no such file or directory, stat '/Users/benoit/Sandboxes/my-vapper-app/vapper.config.js'
    at Object.statSync (fs.js:1086:3)
    at PluginApi.loadConfig (/Users/benoit/Sandboxes/my-vapper-app/node_modules/@vapper/core/lib/PluginApi.js:92:33)
    at Object.<anonymous> (/Users/benoit/Sandboxes/my-vapper-app/node_modules/@vapper/core/bin/cli.js:8:26)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/Users/benoit/Sandboxes/my-vapper-app/vapper.config.js'
}
Error: ENOENT: no such file or directory, stat '/Users/benoit/Sandboxes/my-vapper-app/vapper.config.js'
    at Object.statSync (fs.js:1086:3)
    at Vapper.loadConfig (/Users/benoit/Sandboxes/my-vapper-app/node_modules/@vapper/core/lib/PluginApi.js:92:33)
    at new Vapper (/Users/benoit/Sandboxes/my-vapper-app/node_modules/@vapper/core/lib/index.js:42:12)
    at CAC.<anonymous> (/Users/benoit/Sandboxes/my-vapper-app/node_modules/@vapper/core/bin/cli.js:45:20)
    at CAC.runMatchedCommand (/Users/benoit/Sandboxes/my-vapper-app/node_modules/cac/dist/index.js:597:34)
    at CAC.parse (/Users/benoit/Sandboxes/my-vapper-app/node_modules/cac/dist/index.js:526:12)
    at Object.<anonymous> (/Users/benoit/Sandboxes/my-vapper-app/node_modules/@vapper/core/bin/cli.js:64:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/Users/benoit/Sandboxes/my-vapper-app/vapper.config.js'
}
debug Run Builder in development mode.
debug You have not installed any Configer, will use the default configer: @vapper/configer-vue-cli
debug Write a enhance file: /Users/benoit/Sandboxes/my-vapper-app/node_modules/@vapper/core/app/.vapper/enhanceClient.js
debug Write a enhance file: /Users/benoit/Sandboxes/my-vapper-app/node_modules/@vapper/core/app/.vapper/enhanceServer.js

✔ Client
  Compiled successfully in 2.52s

✔ Server
  Compiled successfully in 2.37s

 DONE  Compiled successfully in -8749ms                                                                                                                                                                                      09:55:46

 DONE  Compiled successfully in -8671ms                                                                                                                                                                                      09:55:46

file                             size    gzipped
dist/vue-ssr-server-bundle.json  390 kB  71.5 kB
(total)                          390 kB  71.5 kB
file                               size     gzipped
dist/favicon.ico                   4.29 kB  864 B
dist/index.html                    943 B    443 B
dist/js/0.js                       27.2 kB  3.15 kB
dist/js/app.js                     20.5 kB  3.06 kB
dist/js/chunk-vendors.js           641 kB   155 kB
dist/js/runtime~app.js             37.1 kB  7.39 kB
dist/vue-ssr-client-manifest.json  4.32 kB  965 B
(total)                            736 kB   171 kB
debug Server bundle and client manifest generated successfully
error Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/benoit/Sandboxes/my-vapper-app/node_modules/@babel/runtime/helpers/esm/defineProperty.js
require() of ES modules is not supported.
require() of /Users/benoit/Sandboxes/my-vapper-app/node_modules/@babel/runtime/helpers/esm/defineProperty.js from /Users/benoit/Sandboxes/my-vapper-app/node_modules/vue-server-renderer/build.dev.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename defineProperty.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/benoit/Sandboxes/my-vapper-app/node_modules/@babel/runtime/helpers/esm/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at r (/Users/benoit/Sandboxes/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:9315:16)
    at Object.@babel/runtime/helpers/esm/defineProperty (webpack:/external "@babel/runtime/helpers/esm/defineProperty":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../node_modules/@babel/runtime/helpers/esm/objectSpread2.js (app.js:199:99)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../node_modules/@vapper/core/app/serverEntry.js (app.js:691:148)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.0 (app.js:4432:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at app.js:118:18
    at Object.<anonymous> (app.js:121:10) {
  code: 'ERR_REQUIRE_ESM'
}
info Server running at: http://0.0.0.0:4000
```

</p>
</details>

<img width="1620" alt="Capture d’écran 2020-11-11 à 09 58 26" src="https://user-images.githubusercontent.com/5569077/98790827-8680f700-2404-11eb-9cd9-b04e45c9b174.png">

The app is served at the end but just doesn't work, clicking on any route throws an error.

At first, it barks because `vapper.config.js` does not exist. Setting an empty one prevents it from shouting again. 
If that step is missing in the documentation I'd be glad to contribute.

Then, that weird error `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module` is thrown. I tried to google it but I didn't find anything relevant to understand it/fix it.

If possible, I'd like to avoid poi because I'm completely unfamiliar with it and it looks a little "black box" to me, as opposed to vue-cli.

Did I miss something? Filling a config file, installing some dependency? I'm pretty sure I followed every step of your guide.

Here are the versions I use:
```
Node:  v14.15.0
NPM: 6.14.8
Yarn: 1.22.10
Vue CLI: @vue/cli 4.5.8
```

Thanks a lot!
Ben

PS: Here's the [repo](https://github.com/bpolaszek/my-vapper-app), if it may help.

**Comment by nannan9507** [comment]
我有同上相同的问题，早些时候部署都是好的，突然在某一次部署出现了这个错误，回退node版本均无法解决

**Comment by bpolaszek** [comment]
I finally migrated to Universal Vue because I had to move forward, and it works, but I admit I preferred the Vapper approach (per-route SSR/SPA instead of SPA URL patterns).

**Comment by auven** [comment]
是 `@vue/cli` 和 `babel` 的相关问题，可以查看这两个 issues ：
- [vue-server-renderer can not import @babel/runtime esm helpers](https://github.com/vuejs/vue-cli/issues/6018)
- [Vue-server-render throws ERR_REQUIRE_ESM error on importing @babel/runtime](https://github.com/babel/babel/issues/12223)

我将 `babel.config.js` 修改成下面的可以正常运行：
``` js
module.exports = {
  presets: [
    // '@vue/cli-plugin-babel/preset'
    [
      '@vue/cli-plugin-babel/preset',
      {
        useBuiltIns: 'entry'
      }
    ]
  ]
}
```

**Comment by bpolaszek** [comment]
Thank you, it does the trick. 👍
