### ISSUE TITLE
按官网Usage跑起来报错

### ISSUE THREAD

**Issue by DMQ** [shuidi-fed/vapper#25]
按官网指引：https://vapperjs.org/zh/usage.html#%E9%9B%86%E6%88%90%E5%88%B0-vue-cli-3-%E9%A1%B9%E7%9B%AE

1(新项目)，2，3步配置好后，通过以下命令跑起来：
```bash
npm run build && npm run start
```

报以下错误：
```bash
debug Run Builder in production mode.
debug You have not installed any Configer, will use the default configer: `@vapper/configer-vue-cli`
error TypeError: Cannot read property 'pluginRuntimeOptions' of undefined
    at app.js:1:10405
    at tryCatch (/data/my-vapper-app/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/data/my-vapper-app/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/data/my-vapper-app/node_modules/regenerator-runtime/runtime.js:97:21)
    at tryCatch (/data/my-vapper-app/node_modules/regenerator-runtime/runtime.js:45:40)
    at invoke (/data/my-vapper-app/node_modules/regenerator-runtime/runtime.js:135:20)
    at /data/my-vapper-app/node_modules/regenerator-runtime/runtime.js:170:11
    at new Promise (<anonymous>)
    at callInvokeWithMethodAndArg (/data/my-vapper-app/node_modules/regenerator-runtime/runtime.js:169:16)
    at AsyncIterator.enqueue [as _invoke] (/data/my-vapper-app/node_modules/regenerator-runtime/runtime.js:192:13)
    at AsyncIterator.prototype.(anonymous function) [as next] (/data/my-vapper-app/node_modules/regenerator-runtime/runtime.js:97:21)
    at Object.exports.async (/data/my-vapper-app/node_modules/regenerator-runtime/runtime.js:216:14)
    at t.default (node_modules/@vapper/core/app/serverEntry.js:19:25)
    at /data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:9391:15
    at new Promise (<anonymous>)
    at /data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:9353:14
info Server running at: http://0.0.0.0:4000
```

**Comment by HcySunYang** [comment]
你好需要安装 [入口文件](https://vapperjs.org/zh/entry.html#%E5%85%A5%E5%8F%A3%E6%96%87%E4%BB%B6) 的描述修改你的代码。

**Comment by DMQ** [comment]
> 你好需要安装 [入口文件](https://vapperjs.org/zh/entry.html#%E5%85%A5%E5%8F%A3%E6%96%87%E4%BB%B6) 的描述修改你的代码。

建议完善下模板，不需要用户再进行修改模板

**Comment by DMQ** [comment]
覆盖了main.js，还是有问题：
```
debug Server rendering encountered an error: { TypeError: Cannot read property 'replace' of undefined
    at normalizeFile (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:9083:27)
    at Array.map (<anonymous>)
    at TemplateRenderer.getUsedAsyncFiles (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:9069:54)
    at TemplateRenderer.getPreloadFiles (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:8963:29)
    at TemplateRenderer.renderPreloadLinks (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:8974:20)
    at TemplateRenderer.renderResourceHints (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:8959:15)
    at TemplateRenderer.render (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:8915:12)
    at RenderContext.done (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:9177:42)
    at RenderContext.next (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:2588:19)
    at RenderContext.cachedWrite [as write] (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:2451:9)
    at RenderContext.next (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:2602:25)
    at RenderContext.cachedWrite [as write] (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:2451:9)
    at RenderContext.next (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:2602:25)
    at RenderContext.cachedWrite [as write] (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:2451:9)
    at RenderContext.next (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:2602:25)
    at RenderContext.cachedWrite [as write] (/data/my-vapper-app/node_modules/vue-server-renderer/build.dev.js:2451:9) isVapper: true }
debug Will fall back SPA mode, url is: /
debug 
        proxy: /js/app.ea009bd1.js
        to: /js/app.ea009bd1.js
      
debug 
        proxy: /js/chunk-vendors.2c112046.js
        to: /js/chunk-vendors.2c112046.js
      
debug 
        proxy: /favicon.ico
        to: /favicon.ico
```

**Comment by HcySunYang** [comment]
[常见问题](https://vapperjs.org/zh/troubleshooting.html#vue-server-render-%E6%8A%A5%E9%94%99-con-t-read-replace-property-on-undefined)
