### ISSUE TITLE
custom-server-express demo 升级到1.3.0版本后无法正常运行

### ISSUE THREAD

**Issue by fa-ge** [shuidi-fed/vapper#72]
**Describe the bug**
访问启动后的服务报错
debug Server rendering encountered an error: { Error: render function or template not defined in component: anonymous
    at normalizeRender (/Users/yonglizhou/Desktop/vapper/examples/custom-server-express/node_modules/_vue-server-renderer@2.6.11@vue-server-renderer/build.dev.js:8262:13)
    at render (/Users/yonglizhou/Desktop/vapper/examples/custom-server-express/node_modules/_vue-server-renderer@2.6.11@vue-server-renderer/build.dev.js:8653:5)
    at Object.renderToString (/Users/yonglizhou/Desktop/vapper/examples/custom-server-express/node_modules/_vue-server-renderer@2.6.11@vue-server-renderer/build.dev.js:9183:9)
    at /Users/yonglizhou/Desktop/vapper/examples/custom-server-express/node_modules/_vue-server-renderer@2.6.11@vue-server-renderer/build.dev.js:9549:22
    at process._tickCallback (internal/process/next_tick.js:68:7) isVapper: true }
debug Will fall back SPA mode, url is: /

**Comment by fa-ge** [comment]
main.js 改了最新的写法解决了
