### ISSUE TITLE
custom server cant do  with http-proxy-middleware

### ISSUE THREAD

**Issue by xurwxj** [shuidi-fed/vapper#89]
**Describe the bug**

i use http-proxy-middleware with vapper:
```
const express = require('express');
const app = express();
const Vapper = require('@vapper/core');

async function starter () {
  // 1. Create a Vapper instance and Vapper will automatically load the configuration file
  const vapper = new Vapper({ mode: process.env.NODE_ENV || 'production' });

  // 2. using the default or from the port and host in the configuration file,
  //    you can also manually specify the port and host
  const {
    options: {
      port,
      host
    }
  } = vapper;

  // 3. Waiting for Vapper setup is complete
  await vapper.setup()

  const { createProxyMiddleware } = require('http-proxy-middleware');
  const cEnv = require("./conf");


  vapper.handler.use("/api", createProxyMiddleware({
    target: cEnv.api.url, 
    changeOrigin: true,
    secure: false,
    headers: {
        "X-Auth-AppID": process.env.AppId || cEnv.api.appId
    },
    pathRewrite: {
        '^/api/': '/'
    }
  }));

  // 4. Use the vapper.handler function to handle the request
  
  app.get('*', vapper.handler);

  // 5. Listening
  app.listen(port, host, () => vapper.logger.info(`Server running at: http://${host}:${port}`));
}

starter();
```

**To Reproduce**

**Expected behavior**

hope all /api be done by createProxyMiddleware.
**Screenshots**

**Additional context**

**Comment by HcySunYang** [comment]
You can register the proxy middleware directly on the express app(instance):

```js
const express = require('express');
const app = express();
const Vapper = require('@vapper/core');

app.use("/api", createProxyMiddleware({
    target: cEnv.api.url, 
    changeOrigin: true,
    secure: false,
    headers: {
        "X-Auth-AppID": process.env.AppId || cEnv.api.appId
    },
    pathRewrite: {
        '^/api/': '/'
    }
}))
```

**Comment by xurwxj** [comment]
still got following err:
```
info Server running at: http://0.0.0.0:9999
---- Only console on the server ----
error Server rendering encountered an error:
error
      =============== Error Start ===============
       Error [VapperError]: Page Not Found
    at new VapperError (node_modules/@vapper/core/app/VapperError.js:6:27)
    at _callee$ (node_modules/@vapper/core/app/serverEntry.js:77:10)
    at tryCatch (/Users/shining3d/projects/vapper/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/shining3d/projects/vapper/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/Users/shining3d/projects/vapper/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:24)
    at _next (node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'VapperError',
  url: '/api/st',
  code: 404,
  message: 'Page Not Found'
}
      =============== Error End =================
debug Will fall back the SPA mode, url is: /api/st
```

server.js:
```
const express = require('express');
const app = express();
const Vapper = require('@vapper/core');

async function starter() {
  // 1. Create a Vapper instance and Vapper will automatically load the configuration file
  const vapper = new Vapper({
    mode: process.env.NODE_ENV || 'production'
  });

  // 2. using the default or from the port and host in the configuration file,
  //    you can also manually specify the port and host
  const {
    options: {
      port,
      host
    }
  } = vapper;

  // 3. Waiting for Vapper setup is complete
  await vapper.setup()

  // const { createProxyMiddleware } = require('http-proxy-middleware');
  // const cEnv = require("./conf");


  app.use('/api', createProxyMiddleware({
    target: cEnv.api.url,
    changeOrigin: true,
    secure: false,
    headers: {
      "X-Auth-AppID": process.env.AppId || cEnv.api.appId
    },
    pathRewrite: {
      '^/api/': '/'
    }
  }));

  // 4. Use the vapper.handler function to handle the request

  app.get('*', vapper.handler);

  // 5. Listening
  app.listen(port, host, () => vapper.logger.info(`Server running at: http://${host}:${port}`));
}

starter();
```

HelloWorld.vue:
```
<template>
  <div class="hello">
    <h1>Hello Home</h1>
    <el-button type="primary" @click="changeLang">主要按钮</el-button>
    message: {{$t("message")}}
    <br />res: {{res}}
    <br />result: {{result}}
  </div>
</template>

<script>
function fetch() {
  return new Promise(resolve => {
    console.log("---- Only console on the server ----");
    setTimeout(() => {
      resolve({
        code: 0,
        data: { foo: 1 }
      });
    }, 200);
  });
}
export default {
  name: "HelloWorld",
  methods: {
    changeLang() {
      // console.log(this);
      if (this.$i18n.locale === "en") {
        this.$i18n.locale = "cn";
      } else {
        this.$i18n.locale = "en";
      }
    },
    async fetchPST() {
      // return "sss";
      await this.$httpGet({
        url: "/api/st",
        validateStatus: function(status) {
          return status >= 200 && status < 404; // default
        }
      }).then(res => {
        // console.log(this);
        console.log("fetchPST: ", res);
        if (res.status === "success") {
          return res.result;
        }
      });
    }
  },
  data() {
    return {
      res: {},
      result: ""
    };
  },
  needSerialize: true,
  async created() {
    this.res = await fetch();
    this.result = await this.fetchPST();
  },
  head: {
    title: "Home"
  }
};
</script>
```

package.json:
```
{
  "name": "vapper-vue-cli-examples",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "vapper dev",
    "build": "vapper build",
    "start": "vapper start"
  },
  "dependencies": {
    "@vapper/core": "^1.2.1",
    "core-js": "^3.4.2",
    "element-ui": "^2.4.5",
    "express": "^4.17.1",
    "http-proxy-middleware": "^1.0.3",
    "js-cookie": "^2.2.1",
    "moment": "^2.24.0",
    "request-promise": "^4.2.5",
    "vue": "^2.6.10",
    "vue-i18n": "^8.0.0",
    "vue-router": "^3.1.3",
    "vue-simple-uploader": "^0.7.4"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.0.0",
    "@vue/cli-service": "^4.0.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.0.3",
    "vue-template-compiler": "^2.6.10"
  }
}
```

**Comment by HcySunYang** [comment]
Maybe you need to use `/api/**`:
```js
app.use('/api/**', createProxyMiddleware({ /* ... */ })
```

**Comment by xurwxj** [comment]
@HcySunYang  still got: 
```
info Server running at: http://0.0.0.0:9999
---- Only console on the server ----
error Server rendering encountered an error:
error
      =============== Error Start ===============
       Error [VapperError]: Page Not Found
    at new VapperError (node_modules/@vapper/core/app/VapperError.js:6:27)
    at _callee$ (node_modules/@vapper/core/app/serverEntry.js:77:10)
    at tryCatch (/Users/shining3d/projects/vapper/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/shining3d/projects/vapper/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/Users/shining3d/projects/vapper/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:24)
    at _next (node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'VapperError',
  url: '/api/st',
  code: 404,
  message: 'Page Not Found'
}
      =============== Error End =================
debug Will fall back the SPA mode, url is: /api/st
```

**Comment by HcySunYang** [comment]
Can you provide a minimal reproduction that runnable?

**Comment by xurwxj** [comment]
@HcySunYang 
https://github.com/xurwxj/vapper

**Comment by HcySunYang** [comment]
Update your script in package.json:
```js
"scripts": {
    "dev": "NODE_ENV=development node ./server.js",
    "build": "vapper build",
    "start": "vapper start"
  },
```

**Comment by xurwxj** [comment]
@HcySunYang tks a lot.
should i change fetch data from created to mounted? when switch from home to dd, i cant got the data again.

**Comment by xurwxj** [comment]
err: 
```
error Server rendering encountered an error:
error
      =============== Error Start ===============
       Error
    at new NavigationDuplicated (/Users/shining3d/projects/vapper/node_modules/vue-router/dist/vue-router.common.js:2014:14)
    at AbstractHistory.confirmTransition (/Users/shining3d/projects/vapper/node_modules/vue-router/dist/vue-router.common.js:2130:18)
    at AbstractHistory.transitionTo (/Users/shining3d/projects/vapper/node_modules/vue-router/dist/vue-router.common.js:2074:8)
    at AbstractHistory.push (/Users/shining3d/projects/vapper/node_modules/vue-router/dist/vue-router.common.js:2625:10)
    at /Users/shining3d/projects/vapper/node_modules/vue-router/dist/vue-router.common.js:2817:22
    at new Promise (<anonymous>)
    at VueRouter.push (/Users/shining3d/projects/vapper/node_modules/vue-router/dist/vue-router.common.js:2816:12)
    at _callee$ (node_modules/@vapper/core/app/serverEntry.js:63:15)
    at tryCatch (/Users/shining3d/projects/vapper/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/shining3d/projects/vapper/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/Users/shining3d/projects/vapper/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:24)
    at _next (node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:8)
    at app.js:223:7
    at new Promise (<anonymous>)
    at app.js:212:12
    at app.js:1152:17
    at /Users/shining3d/projects/vapper/node_modules/vue-server-renderer/build.dev.js:9406:15
    at new Promise (<anonymous>)
    at /Users/shining3d/projects/vapper/node_modules/vue-server-renderer/build.dev.js:9368:14
    at Object.renderToString (/Users/shining3d/projects/vapper/node_modules/vue-server-renderer/build.dev.js:9544:9)
    at /Users/shining3d/projects/vapper/node_modules/@vapper/core/lib/index.js:268:23 {
  _name: 'NavigationDuplicated',
  name: 'NavigationDuplicated',
  message: 'Navigating to current location ("/") is not allowed'
}
      =============== Error End =================
debug Will fall back the SPA mode, url is: /
error Server rendering encountered an error:
```

**Comment by HcySunYang** [comment]
Server-side rendering needs to avoid state singletons, Modify `router/index.js` and make it return a creator function:
```js
export default function createRouter() {
  return new VueRouter({
    mode: 'history',
    base: process.env.BASE_URL,
    routes
  })
}
```

then in the `src/index.js`:

```js
import createRouter from './router/index'

export default function createApp () {
  const app = {
    router: createRouter(),
    // ...
  }

  // 3. return
  return app
}
```

**Comment by xurwxj** [comment]
@HcySunYang i've updated my repo according your advise above, changes only valid for first load or refresh page, when switch between home and dd, got following:
![image](https://user-images.githubusercontent.com/683421/78208937-3d64de00-74d8-11ea-8a27-f577e991e16f.png)

first loading or refresh:
![image](https://user-images.githubusercontent.com/683421/78208961-4f468100-74d8-11ea-8008-f9b2971089ca.png)

**Comment by xurwxj** [comment]
@HcySunYang tks a lot

**Comment by xurwxj** [comment]
@HcySunYang I've update my repo according your advise above, but cant load data when switch between home and dd, got following screenshot:
![image](https://user-images.githubusercontent.com/683421/78209987-4b682e00-74db-11ea-89c7-6bf06d9c3465.png)

all done well when first loading of home.
