### ISSUE TITLE
Not compatible with @vue/cli-plugin-pwa

### ISSUE THREAD

**Issue by cslee** [shuidi-fed/vapper#97]
**Describe the bug**
Exception occurs when @vue/cli-plugin-pwa is included in the project

**To Reproduce**
Take [vapper-vue-cli-example](https://github.com/shuidi-fed/vapper-vue-cli-example) project as an example
1. Run `npm i @vue/cli-plugin-pwa -D`
2. Run `npm dev`

Exception:
```
(node:95859) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tapAsync' of undefined
    at /Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js:62:63
    at SyncHook.eval [as call] (eval at create (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/webpack/lib/Watching.js:41:32)
    at /Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/webpack/lib/Watching.js:33:9
    at Compiler.readRecords (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/webpack/lib/Compiler.js:529:11)
    at new Watching (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/webpack/lib/Watching.js:30:17)
    at Compiler.watch (/Users/xxxxxx/dev/vapper-vue-cli-example/node_modules/webpack/lib/Compiler.js:244:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:95859) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:95859) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cslee** [comment]
Duplicate with #38
